name: CI/CD for Payment Microservice

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build -f ../MSA-6/payment_service/Dockerfile --tag cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest ../MSA-6

      - name: Login to YC Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: cr.yandex
          username: json_key
          password: ${{ secrets.YC_KEYS }}

      - name: Push tag YC Registry
        run: |
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment_service:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
    - name: Deploy serverless container
      uses: yc-actions/yc-sls-container-deploy@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_KEYS }}
        container-name: ${{ secrets.YC_CONTAINER_NAME }}
        folder-id: ${{ secrets.YC_FOLDER_ID }}
        revision-image-url: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/payment-service:latest
        revision-service-account-id: ${{ secrets.YC_SA_ID }}
  